src/DateRange.js

Reverts Adphorus/react-date-range#6

Revert "Bug/range not updated"

---

README.md

In #9 I forgot to change line number to the theme demo source.

Fix link to theme demo.

---

lib/Calendar.js
src/Calendar.js

Change the previous month's days calculation to include the last day of the previous month

---

lib/Calendar.js
lib/DayCell.js
lib/styles.js
src/Calendar.js
src/DayCell.js
src/styles.js

Support identification and styling today's date

---

demo/src/components/Main.js
lib/Calendar.js
lib/DateRange.js
src/Calendar.js
src/DateRange.js

Support marking dates before a min and max date as passive.

---

demo/build.js
demo/src/components/Main.js
lib/Calendar.js
lib/DateRange.js
lib/DayCell.js
lib/PredefinedRanges.js
lib/styles.js
src/Calendar.js
src/DateRange.js
src/DayCell.js
src/PredefinedRanges.js
src/styles.js

See #17 and #20 
This resolves the invariant exception noted in the latter.

Configurable Classes (Round 2)

---

lib/styles.js
src/styles.js

Hi, great work on this component!
I would like to be able to add 'margin' to the Day Cells.
This PR makes it possible
Thanks!

allow Day cells to have margin

---

lib/DayCell.js
src/DayCell.js

See attached gif of the problem in action.

Fix clicking edge of day cell

---

README.md

Hey 
I was looking through the source code for a way to add min and max date and I noticed you have already added it. I have added it to the documentation, love the plugin :).

Added min and max date to documentation

---

demo/build.js
demo/package.json
demo/src/components/Main.js
demo/src/index.html
demo/src/styles/global.css
src/styles.scss

Updated Demo config. to handle SCSS.

Adding SCSS for 'classesOnly' prop.

---

lib/Calendar.js
src/Calendar.js

Closes https://github.com/Adphorus/react-date-range/issues/60

Redraw calendar when range changes

---

lib/Calendar.js
lib/DayCell.js
lib/styles.js
lib/utils/parseInput.js
src/Calendar.js
src/DayCell.js
src/styles.js

colorful Sunday

---

lib/DayCell.js
src/DayCell.js

The regression was introduced in https://github.com/Adphorus/react-date-range/pull/51/files

Disable dayWrapperStyles when onlyClasses is true

---

README.md
lib/Calendar.js
lib/DateRange.js
src/Calendar.js
src/DateRange.js

I've added a new prop which ensures that first calendar is always attached to the startDate and the last one - to endDate.

Introduce rangedCalendars prop

---

README.md
demo/src/components/Main.js

- update documentation for internationalization
- fix a typo in an internationalization demo example
based on this [Pull Request](https://github.com/Adphorus/react-date-range/pull/81/commits/ae663d2e6b3c4664f55d17d8b7e490c6603f82a6)

Update document and demo related to internationalization

---

lib/Calendar.js
src/Calendar.js

Fix localisation lookups for languages not in LangDic

---

README.md

https://github.com/Adphorus/react-date-range/pull/108 Colorful Special Days

README - specialDays prop

---

README.md
lib/LangDic.js
src/LangDic.js

I have added support for spanish language.

Added spanish language

---

src/LangDic.js

Implementation of the Portuguese language in the project

Implementation of the language Portugues Brasil

---

src/LangDic.js

I've just added the Portuguese translations to the calendar.

Adding Portuguese language support

---

README.md
src/LangDic.js

Added Finnish language support. Also fixed a missing comma.

Added finnish support

---

README.md
demo/src/components/Main.js
src/components/Calendar.js
src/components/DateInput.js
src/components/dateInput.scss
src/styles.scss

Created a `DateInput` component where users can enter the dates manually using the specified date format.
> Related Issue: #279

Added editable DateInput components to Calendar

---

jest.config.js
src/components/DefinedRange.js
src/components/InputRangeField.js
src/components/InputRangeField.test.js
src/components/__snapshots__/DefinedRange.test.js.snap
src/components/__snapshots__/InputRangeField.test.js.snap

Created a `InputRangeField` component that renders custom input range options.
Input field now has a placeholder that would be shown when an input range has no value
> Related Issue: #278

Input range field changes

---

README.md
src/components/Calendar/index.js
src/components/Month/index.js

Predicate function that disable day fn(date: Date). For example, we need to enable us to select only Mondays. The function very helpful instead of disabledDates array.
> Related Issue: #405

add disableDay function

---

.github/workflows/tests.yml

Add Github Actions Workflow for tests

add GH test workflow

---

.github/CODEOWNERS
CHANGELOG.md
README.md
package.json
src/components/DateRangePicker/README.md

Release 1.2.0

---

src/components/DateRange/index.js
src/components/DateRangePicker/README.md

Add date disabling to demo

---

.github/workflows/demo.yml
.gitignore
README.md

- Fixing missing doc 
- Auto deploy github pages

add missing doc + gh pages deployment

---

CHANGELOG.md
package.json

v1.4.0 prep

---

README.md

Just a `typo` fix in `README.md` file.

Fix typo in `README.md` file
