hypeserver/react-date-range

README.md, demo/src/components/Main.js, lib/Calendar.js, lib/DateRange.js, src/Calendar.js, src/DateRange.js
Hi there.
Would just like to start by saying great package. :+1: Been looking for a pure React calendar component. All other calendars have been using bootstrap or some other frameworks.
I would really like to change the first day of week without changing global moment locale. This is a deal breaker for our company. I created this patch, but feel free to change the implementation.
:smile:
=> Change first day of week through props.

package.json
This will allow users to use this repo with newest version of React.
Tested in 0.14.2 and everything looks great.
=> Support newer version of React by default.

.gitignore, lib/Calendar.js, src/Calendar.js
Currently when the Calendar component is inside of a form it will submit the form, now preventing default action on changeMonth.
=> Prevent default when changing month

demo/build.js, demo/src/components/Main.js, lib/Calendar.js, lib/DateRange.js, lib/DayCell.js, lib/PredefinedRanges.js, lib/styles.js, package.json, src/Calendar.js, src/DateRange.js, src/DayCell.js, src/PredefinedRanges.js, src/styles.js
This is intended to solve #12 
Each class name in the code base is now configurable via props ([much like](https://facebook.github.io/react/docs/animation.html#custom-classes))
This has the nice side effect of fully supporting [CSS Modules](https://github.com/css-modules/css-modules)
I also went ahead and added the `onlyClasses` prop discussed in the issue
=> Configurable Classes

demo/build.js, demo/src/components/Main.js, lib/Calendar.js, lib/DateRange.js, lib/DayCell.js, lib/PredefinedRanges.js, lib/styles.js, package.json, src/Calendar.js, src/DateRange.js, src/DayCell.js, src/PredefinedRanges.js, src/styles.js
Reverts Adphorus/react-date-range#17
I did try it locally and `onlyClasses={ true }` throwed: 
```
Uncaught Error: Invariant Violation: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.
```
i think this is because of `{ !onlyClasses && {... }` is returning `false` and the style prop becoming `style={false}`
=> Revert "Configurable Classes"

src/Calendar.js, src/PredefinedRanges.js
Great component! When using the "onlyClasses" option, there were just a couple inner components still using inline styles.
=> Enabled "onlyClasses" option for PredefinedRangesItem, MonthArrowPrev, and MonthArrowNext

lib/utils/parseInput.js
This is a tiny change, but after being confused writing component tests for a while, I found this and I figured it was less work to change it than it was to write an issue.
Thanks for the component! It works really well.
=> Stopped parseInput from mutating props

lib/Calendar.js, lib/DateRange.js, lib/PredefinedRanges.js, lib/utils/parseInput.js, src/Calendar.js, src/DateRange.js, src/PredefinedRanges.js, src/utils/parseInput.js
I noticed that all dates are being converted using `startOf` which creates issues for applications using up-to-the-minute timestamps for graphing data. This does not break the previous behavior/experience and allows for the above mentioned use-case.
=> use startOf and endOf for date selection and ranges

lib/Calendar.js, lib/utils/parseInput.js, src/Calendar.js
Related issue: https://github.com/Adphorus/react-date-range/issues/61
Setting locale using `moment.locale('zh-cn');` outside of DateRange component, doesn't affect strings in Calendar when you're using webpack/babel.
I've added a new `locale` property which fixes the issue.
=> Add locale property

src/Calendar.js
Hello,
Since `button` element inside `Calendar` component don't have `type` attribute, they prevent form to be submitted when user presses enter key.
---
Here's an example gif:
---
To fix this behaviour, I've just added `type="button"` attribute to them.
=> Add type attribute to calendar buttons

README.md, lib/DateRange.js, src/DateRange.js
This PR adds a prop to the date range component which allows it to call the `onChange` event only when both start and end dates have been explicitly set.
=> Add a prop to call onChange only when the step is 0

lib/Calendar.js, src/Calendar.js
Calendar component does not correctly mark today's date as today, because it compares the end of today to the start of the day being displayed.
=> Fix bug in Calendar's "isToday" check

src/LangDic.js
Append missing comma in `LangDic.js` file between Korean and Spanish.
=> Add missing comma in LangDic.js

src/LangDic.js
The correct italian translation for 'tuesday' is 'Martedì', not 'Mardi'
=> Updated LangDic.js

src/components/Calendar.js
We are using react-date-range in one of our projects and we have a scenario where we needed to disable/hide the next month arrow when looking at the current month. 
This PR adds a prop `onShownDateChange` which is a function that is called when the shown date changes via navigation.
=> Added callback prop for announcing when the shown date gets changed.

src/components/Month.js
Hello,
I noticed the month name wasn't localized when displayed.
After further inspection, I noticed the dateOptions weren't passed through to this format call, so here's a quickfix to solve this.
Have a good day !
=> Pass dateOptions to the month name format call

README.md, src/components/Calendar.js
Adding a prop 'showMonthAndYearPickers' default to 'true'. If set to true nothing changes, if set to false it removes the month and year select tags and replaces them with span tags showing the month and year.
> Related Issue: #205
=> adding a prop to allow disabling the month and year selectors

README.md, demo/src/components/Main.js, src/components/Calendar.js
We have a use case where we need to prevent the user from dragging to select a date range. This `dragSelectionEnabled` property, which is true by default, determines whether to allow drag-based selection.
=> Allow disabling of drag-based selection

src/components/Calendar.js
On firefox browsers, year picker is not working because the `onMouseUp` event that exists on calendar container, de-attached the target value of year picker. So I stopped the propagation on Year and Month pickers containers.
> Related Issue: #201
=> Firefox month/year selection bug

CHANGELOG.md, README.md, demo/src/components/Main.js, src/components/Calendar.js, src/components/DateRange.js, src/components/Month.js
- Added a `disabledDates` props which holds an array of dates to be disabled. These days will be rendered with the disabled props.
- Also handles the case when you would select a range that includes one of the disabled dates.
- Added an example using this feature to the demo
> Related Issue: #213
=> Enable disabling of certain dates

. eslintignore, CONTRIBUTING.md, README.md, demo/src/components/Main.js, package.json, src/components/DefinedRange.js, src/components/DefinedRange.test.js, src/components/__snapshots__/DefinedRange.test.js.snap, yarn.lock
`renderStaticRangeLabel` callback prop is added to `DefinedRange` component to enable custom component rendering for static range labels.
-`react-test-renderer` is added to dev dependencies.
-Initial `DefinedRange` tests are added.
-README is updated for `renderStaticRangeLabel`.
-eslintignore file is updated to ignore snapshot files.
-Existing demo is updated to display new `renderStaticRangeLabel` usage.
=> Support for customizable static range labels

src/components/DateRangePicker/index.js
Fixed wrong daterange on hover bug by processing value through `calcNewSelection` before feeding into `updatePreview`. Used `typeof value === "string"` to determine whether the `isSingleValue`.  
> Related Issue: #368
=> Fix wrong daterange on hover bug

.babelrc, .gitignore, package.json, yarn.lock
Reduces number of bundled date-fns functions to only the ones actually used, in the below case the size dropped by 10kb gzipped
> Related Issue: #356
=> Use babel-plugin-date-fns to reduce bundle size

src/components/InputRangeField/index.js, src/components/InputRangeField/index.test.js
Added the possibility to add the `label` prop as a Component
In order to have the possibility to use a *Component* as the label of `InputRangeField`, I'm proposing this change:
```JS
PropTypes.oneOfType([PropTypes.element, PropTypes.node]).isRequired,
```
So that you can use something like this: 
```
const defaultInputRanges = [
{
label: <MyFancyReactComponent />,
...
}
]
```
thank you :+1:
=> feat: InputDateRange label as a Component

src/components/DateRangePicker/README.md, src/components/DayCell/index.js
Adds support for passing a function to customize DayCell content.
> Related Issue: #242
=> Add support for customising the DayCell

README.md, src/components/DateRange/README.md, src/components/DateRange/index.js, src/components/DateRange/index.test.js
------- 
The user might want to move the start date without moving the end date, but the component is currently resetting the end date in all start date changes, which is not the ideal behavior in my opinion. See below a few gifs explaining the issue below:
How Google Analytics date selection behaves, (keeps end date selection):
How the current component behaves when the start date is changed:
After this PR:
We might want to bump at least minor version as this changes the behavior, in order to improve functionality.
> Related Issue: https://github.com/hypeserver/react-date-range/issues/464
=> Update range selection behavior

CHANGELOG.md, package.json
=> 1.3.0 updates
